language: objective-c
osx_image: xcode9
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
script:
   - bash -x ./scripts/build_sample.sh Conversation-Samples ConversationDemo ConversationDemo
   - bash -x ./scripts/build_sample.sh Conversation-Samples ConversationPrivateInfo ConversationPrivateInfoApp
   - bash -x ./scripts/build_sample.sh Conversation-Samples HistorySample HistorySample
   - bash -x ./scripts/build_sample.sh CustomViewComponents "" CustomViewComponents
   - bash -x ./scripts/build_sample.sh SearchDemo "" SearchDemo
   

notifications:
  email:
    recipients:
      - eliza.koren@logmein.com
      - Nissim.Pardo@logmein.com
      - Tony.Shlifstein@logmein.com
      - Oz.BenOved@logmein.com
    on_success: change
    on_failure: always
