language: objective-c
osx_image: xcode9
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
script:
   - bash -x ./scripts/build_sample.sh Conversation-Samples ConversationDemo ConversationDemo

notifications:
  email:
    recipients:
      - eliza.koren@logmein.com
      - Nissim.Pardo@logmein.com
      - Tony.Shlifstein@logmein.com
      - Oz.BenOved@logmein.com
    on_success: change
    on_failure: always
