language: objective-c
osx_image: xcode9
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  # deploy develop to the staging environment
# deploy:
#   - provider: script
script:
   - bash -x ./scripts/build_sample.sh Conversation-Samples ConversationDemo ConversationDemo
#     on:
#       branch: master
# script:
#   - bash scripts/build_sample.sh Conversation-Samples ConversationDemo ConversationDemo
#   - cd Conversation-Samples
#   - cd ConversationDemo
#   - pod update --repo-update
#   - xcodebuild -scheme ConversationDemo -workspace ConversationDemo.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.1'

# notifications:
#   email:
#     recipients:
#       - eliza.koren@logmein.com
#       - Nissim.Pardo@logmein.com
#       - Tony.Shlifstein@logmein.com
#       - Oz.BenOved@logmein.com
#     on_success: change
#     on_failure: always
